create table if not exists workspace_settings (
  id text primary key,
  from_address text not null,
  config_set text not null default 'email-tracking-config-set',
  rate_limit integer not null default 300,
  footer_html text not null default '',
  website_url text not null default ''
);

alter table if exists workspace_settings
  add column if not exists footer_html text not null default '';

alter table if exists workspace_settings
  add column if not exists website_url text not null default '';

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  email text not null,
  fields jsonb not null default '{}'::jsonb,
  unique (workspace_id, email)
);

create table if not exists sends (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  message_id text not null unique,
  recipient text not null,
  subject text not null default '',
  sent_at timestamptz not null default now()
);

create table if not exists email_events (
  id bigint generated by default as identity primary key,
  message_id text not null,
  event_type text not null,
  timestamp timestamptz not null,
  detail text not null default ''
);

create table if not exists workspace_memberships (
  workspace_id text not null,
  user_id uuid not null,
  role text not null default 'member',
  created_at timestamptz not null default now(),
  constraint workspace_memberships_role_check check (role in ('owner', 'member')),
  primary key (workspace_id, user_id)
);

create index if not exists idx_contacts_workspace on contacts(workspace_id);
create index if not exists idx_sends_workspace on sends(workspace_id);
create index if not exists idx_events_message_id on email_events(message_id);
create index if not exists idx_workspace_memberships_user on workspace_memberships(user_id);
