create table if not exists workspace_settings (
  id text primary key,
  from_address text not null,
  config_set text not null default 'email-tracking-config-set',
  rate_limit integer not null default 300,
  footer_html text not null default '',
  website_url text not null default '',
  contact_source_provider text not null default 'manual',
  contact_source_config jsonb not null default '{}'::jsonb
);

alter table if exists workspace_settings
  add column if not exists footer_html text not null default '';

alter table if exists workspace_settings
  add column if not exists website_url text not null default '';

alter table if exists workspace_settings
  add column if not exists contact_source_provider text not null default 'manual';

alter table if exists workspace_settings
  add column if not exists contact_source_config jsonb not null default '{}'::jsonb;

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  email text not null,
  fields jsonb not null default '{}'::jsonb,
  unique (workspace_id, email)
);

create table if not exists sends (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  message_id text not null unique,
  recipient text not null,
  subject text not null default '',
  sent_at timestamptz not null default now()
);

create table if not exists email_events (
  id bigint generated by default as identity primary key,
  message_id text not null,
  event_type text not null,
  timestamp timestamptz not null,
  detail text not null default ''
);

create table if not exists workspace_memberships (
  workspace_id text not null,
  user_id uuid not null,
  role text not null default 'member',
  created_at timestamptz not null default now(),
  constraint workspace_memberships_role_check check (role in ('owner', 'member')),
  primary key (workspace_id, user_id)
);

create table if not exists send_jobs (
  id uuid primary key,
  workspace_id text not null,
  user_id uuid not null,
  status text not null default 'queued'
    check (status in ('queued','running','completed','failed','cancelled')),
  total integer not null default 0,
  sent integer not null default 0,
  failed integer not null default 0,
  dry_run boolean not null default false,
  payload jsonb not null,
  rate_limit integer not null default 300,
  batch_size integer not null default 50,
  send_concurrency integer not null default 4,
  error_message text null,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  heartbeat_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists send_job_recipients (
  id bigint generated by default as identity primary key,
  job_id uuid not null references send_jobs(id) on delete cascade,
  recipient text not null,
  status text not null default 'pending'
    check (status in ('pending','sending','sent','failed')),
  message_id text null,
  error text null,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  processed_at timestamptz,
  last_error_at timestamptz,
  unique (job_id, recipient)
);

create index if not exists idx_contacts_workspace on contacts(workspace_id);
create index if not exists idx_sends_workspace on sends(workspace_id);
create index if not exists idx_events_message_id on email_events(message_id);
create index if not exists idx_workspace_memberships_user on workspace_memberships(user_id);
create index if not exists idx_send_jobs_status_created on send_jobs(status, created_at);
create index if not exists idx_send_jobs_user on send_jobs(user_id, status, created_at);
create index if not exists idx_send_job_recipients_job on send_job_recipients(job_id, status, id);
