create table if not exists workspace_settings (
  id text primary key,
  from_address text not null,
  from_name text not null default '',
  config_set text not null default 'email-tracking-config-set',
  rate_limit integer not null default 300,
  footer_html text not null default '',
  website_url text not null default '',
  contact_source_provider text not null default 'manual',
  contact_source_config jsonb not null default '{}'::jsonb
);

alter table if exists workspace_settings
  add column if not exists from_name text not null default '';

alter table if exists workspace_settings
  add column if not exists footer_html text not null default '';

alter table if exists workspace_settings
  add column if not exists website_url text not null default '';

alter table if exists workspace_settings
  add column if not exists contact_source_provider text not null default 'manual';

alter table if exists workspace_settings
  add column if not exists contact_source_config jsonb not null default '{}'::jsonb;

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  email text not null,
  fields jsonb not null default '{}'::jsonb,
  unique (workspace_id, email)
);

create table if not exists contact_unsubscribes (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  email text not null,
  unsubscribed_at timestamptz not null default now(),
  unique (workspace_id, email)
);

create table if not exists sends (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  message_id text not null unique,
  recipient text not null,
  subject text not null default '',
  sent_at timestamptz not null default now()
);

create table if not exists email_events (
  id bigint generated by default as identity primary key,
  message_id text not null,
  event_type text not null,
  timestamp timestamptz not null,
  detail text not null default ''
);

create table if not exists workspace_memberships (
  workspace_id text not null,
  user_id uuid not null,
  role text not null default 'member',
  created_at timestamptz not null default now(),
  constraint workspace_memberships_role_check check (role in ('owner', 'member')),
  primary key (workspace_id, user_id)
);

create table if not exists send_jobs (
  id uuid primary key,
  workspace_id text not null,
  user_id uuid not null,
  status text not null default 'queued'
    check (status in ('queued','running','completed','failed','cancelled')),
  total integer not null default 0,
  sent integer not null default 0,
  failed integer not null default 0,
  dry_run boolean not null default false,
  payload jsonb not null,
  rate_limit integer not null default 300,
  batch_size integer not null default 50,
  send_concurrency integer not null default 4,
  error_message text null,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  heartbeat_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists send_job_recipients (
  id bigint generated by default as identity primary key,
  job_id uuid not null references send_jobs(id) on delete cascade,
  recipient text not null,
  status text not null default 'pending'
    check (status in ('pending','sending','sent','failed')),
  message_id text null,
  error text null,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  processed_at timestamptz,
  last_error_at timestamptz,
  unique (job_id, recipient)
);

create index if not exists idx_contacts_workspace on contacts(workspace_id);
create index if not exists idx_contact_unsubscribes_workspace on contact_unsubscribes(workspace_id);
create index if not exists idx_sends_workspace on sends(workspace_id);
create index if not exists idx_events_message_id on email_events(message_id);
create index if not exists idx_workspace_memberships_user on workspace_memberships(user_id);
create index if not exists idx_send_jobs_status_created on send_jobs(status, created_at);
create index if not exists idx_send_jobs_user on send_jobs(user_id, status, created_at);
create index if not exists idx_send_job_recipients_job on send_job_recipients(job_id, status, id);

create table if not exists api_keys (
  id uuid primary key default gen_random_uuid(),
  workspace_id text not null,
  key_hash text not null unique,
  key_prefix text not null,
  name text not null default '',
  scopes text[] null,
  created_at timestamptz not null default now()
);

alter table if exists api_keys
  add column if not exists scopes text[] null;

create index if not exists idx_api_keys_workspace on api_keys(workspace_id);
create index if not exists idx_api_keys_key_hash on api_keys(key_hash);

create table if not exists workspace_billing (
  workspace_id text primary key,
  billing_status text not null default 'inactive'
    check (billing_status in ('inactive','active','trialing','past_due','canceled','unpaid')),
  billing_email text not null default '',
  plan_name text not null default 'free',
  credit_balance integer not null default 0,
  lifetime_credits_purchased integer not null default 0,
  lifetime_credits_consumed integer not null default 0,
  polar_customer_id text null,
  polar_external_customer_id text not null unique,
  polar_subscription_id text null,
  polar_subscription_status text null,
  polar_current_period_start timestamptz,
  polar_current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists workspace_billing
  add column if not exists credit_balance integer not null default 0;

alter table if exists workspace_billing
  add column if not exists lifetime_credits_purchased integer not null default 0;

alter table if exists workspace_billing
  add column if not exists lifetime_credits_consumed integer not null default 0;

create index if not exists idx_workspace_billing_status on workspace_billing(billing_status);
create index if not exists idx_workspace_billing_credits on workspace_billing(credit_balance);

create table if not exists workspace_credit_grants (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  source_id text not null unique,
  credits integer not null check (credits > 0),
  amount_cents integer not null default 0,
  currency text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_workspace_credit_grants_workspace
  on workspace_credit_grants(workspace_id, created_at desc);

create or replace function apply_workspace_credit_topup(
  p_workspace_id text,
  p_source_id text,
  p_credits integer,
  p_amount_cents integer default 0,
  p_currency text default '',
  p_metadata jsonb default '{}'::jsonb
) returns boolean
language plpgsql
security definer
as $$
declare
  inserted_count integer := 0;
  normalized_workspace_id text;
begin
  normalized_workspace_id := lower(btrim(coalesce(p_workspace_id, '')));
  if normalized_workspace_id = '' then
    raise exception 'workspace_id is required';
  end if;

  if btrim(coalesce(p_source_id, '')) = '' then
    raise exception 'source_id is required';
  end if;

  if coalesce(p_credits, 0) <= 0 then
    raise exception 'credits must be > 0';
  end if;

  insert into workspace_billing (
    workspace_id,
    polar_external_customer_id
  ) values (
    normalized_workspace_id,
    'workspace:' || normalized_workspace_id
  )
  on conflict (workspace_id) do nothing;

  insert into workspace_credit_grants (
    workspace_id,
    source_id,
    credits,
    amount_cents,
    currency,
    metadata
  ) values (
    normalized_workspace_id,
    p_source_id,
    p_credits,
    greatest(coalesce(p_amount_cents, 0), 0),
    coalesce(p_currency, ''),
    coalesce(p_metadata, '{}'::jsonb)
  )
  on conflict (source_id) do nothing;

  get diagnostics inserted_count = row_count;
  if inserted_count = 0 then
    return false;
  end if;

  update workspace_billing
  set
    credit_balance = greatest(0, credit_balance) + p_credits,
    lifetime_credits_purchased = greatest(0, lifetime_credits_purchased) + p_credits,
    updated_at = now()
  where workspace_id = normalized_workspace_id;

  return true;
end;
$$;

create or replace function consume_workspace_credits(
  p_workspace_id text,
  p_credits integer default 1
) returns table (
  ok boolean,
  balance integer
)
language plpgsql
security definer
as $$
declare
  normalized_workspace_id text;
  updated_balance integer;
  current_balance integer;
begin
  normalized_workspace_id := lower(btrim(coalesce(p_workspace_id, '')));
  if normalized_workspace_id = '' then
    raise exception 'workspace_id is required';
  end if;

  if coalesce(p_credits, 0) <= 0 then
    return query select true, null::integer;
    return;
  end if;

  insert into workspace_billing (
    workspace_id,
    polar_external_customer_id
  ) values (
    normalized_workspace_id,
    'workspace:' || normalized_workspace_id
  )
  on conflict (workspace_id) do nothing;

  update workspace_billing
  set
    credit_balance = credit_balance - p_credits,
    lifetime_credits_consumed = greatest(0, lifetime_credits_consumed) + p_credits,
    updated_at = now()
  where workspace_id = normalized_workspace_id
    and credit_balance >= p_credits
  returning workspace_billing.credit_balance into updated_balance;

  if found then
    return query select true, updated_balance;
    return;
  end if;

  select credit_balance
    into current_balance
  from workspace_billing
  where workspace_id = normalized_workspace_id;

  return query select false, coalesce(current_balance, 0);
end;
$$;

create index if not exists idx_sends_workspace_sent_at on sends(workspace_id, sent_at);

-- Enable Row Level Security on all public tables.
-- The app accesses data exclusively via the service role key (which bypasses RLS),
-- so no policies are needed. This prevents any access through the anon/publishable key.
alter table if exists workspace_settings enable row level security;
alter table if exists contacts enable row level security;
alter table if exists contact_unsubscribes enable row level security;
alter table if exists sends enable row level security;
alter table if exists email_events enable row level security;
alter table if exists workspace_memberships enable row level security;
alter table if exists send_jobs enable row level security;
alter table if exists send_job_recipients enable row level security;
alter table if exists api_keys enable row level security;
alter table if exists workspace_billing enable row level security;
alter table if exists workspace_credit_grants enable row level security;
